# Exercise on Functions:

# Task-1 Unit Conversion

In [5]:
def length_convert(val, unit):
    if unit == 'm_to_ft':
        return val * 3.28084
    elif unit == 'ft_to_m':
        return val / 3.28084
    else:
        raise ValueError("Invalid length unit.")

def weight_convert(val, unit):
    if unit == 'kg_to_lbs':
        return val * 2.20462
    elif unit == 'lbs_to_kg':
        return val / 2.20462
    else:
        raise ValueError("Invalid weight unit.")

def volume_convert(val, unit):
    if unit == 'L_to_gal':
        return val * 0.264172
    elif unit == 'gal_to_L':
        return val / 0.264172
    else:
        raise ValueError("Invalid volume unit.")

def main():
    print("Unit Converter")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        option = int(input("Select a conversion type (1, 2, or 3): "))
        val = float(input("Enter value: "))

        if option == 1:
            unit = input("Choose conversion (m_to_ft / ft_to_m): ")
            result = length_convert(val, unit)
        elif option == 2:
            unit = input("Choose conversion (kg_to_lbs / lbs_to_kg): ")
            result = weight_convert(val, unit)
        elif option == 3:
            unit = input("Choose conversion (L_to_gal / gal_to_L): ")
            result = volume_convert(val, unit)
        else:
            print("Invalid option.")
            return

        print(f"Converted value: {result}")
    except ValueError as err:
        print(f"Error: {err}")

main()


Unit Converter
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Select a conversion type (1, 2, or 3): 1
Enter value: 50
Choose conversion (m_to_ft / ft_to_m): m_to_ft
Converted value: 164.042


# Task-2 Math Operation on List of Numbers

In [6]:
def get_sum(nums):
    """
    Returns the sum of a list of numbers.
    """
    return sum(nums)

def get_avg(nums):
    """
    Returns the average of a list of numbers.
    """
    return sum(nums) / len(nums)

def get_max(nums):
    """
    Returns the maximum value from a list of numbers.
    """
    return max(nums)

def get_min(nums):
    """
    Returns the minimum value from a list of numbers.
    """
    return min(nums)

def main():
    print("Math Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Select an operation (1-4): "))
        nums = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if choice == 1:
            result = get_sum(nums)
            print(f"Sum: {result}")
        elif choice == 2:
            result = get_avg(nums)
            print(f"Average: {result}")
        elif choice == 3:
            result = get_max(nums)
            print(f"Maximum: {result}")
        elif choice == 4:
            result = get_min(nums)
            print(f"Minimum: {result}")
        else:
            print("Invalid selection.")
    except ValueError:
        print("Error: Please enter valid numbers.")
    except ZeroDivisionError:
        print("Error: Cannot compute average of an empty list.")

main()


Math Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Select an operation (1-4): 1
Enter numbers separated by spaces: 50 50
Sum: 100.0


# Exercise on List Manipulation:

In [3]:
def get_every_other(items):
    """
    Returns every other element from the given list, starting with the first.
    """
    return items[::2]

print(get_every_other([1, 2, 3, 4, 5, 6]))


[1, 3, 5]


In [2]:
def sublist(items, start_idx, end_idx):
    """
    Returns a portion of the list from start_idx to end_idx (inclusive).
    """
    return items[start_idx:end_idx+1]

print(sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


In [1]:
def reverse_items(items):
    """
    Returns the reversed version of a list.

    Parameters:
    items (list): List to be reversed.

    Returns:
    list: Reversed list.
    """
    return items[::-1]

reverse_items([1, 2, 3, 4, 5])

[5, 4, 3, 2, 1]

In [4]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The sublist without the first and last elements.
    """
    return lst[1:-1]

remove_first_last([1, 2, 3, 4, 5])

[2, 3, 4]

In [5]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The first n elements of the list.
    """
    return lst[:n]

get_first_n([1, 2, 3, 4, 5],3)

[1, 2, 3]

In [6]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The last n elements of the list.
    """
    return lst[-n:]

get_last_n([1, 2, 3, 4, 5],2)

[4, 5]

In [7]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

reverse_skip([1, 2, 3, 4, 5, 6])

[5, 3, 1]

# Exercise on Nested List

In [9]:
def flatten_list(nested_list):
    """
    Converts a nested list into a single flat list.

    Parameters:
    nested_list (list): A list containing sublists.

    Returns:
    list: A single flattened list.
    """
    result = []
    for element in nested_list:
        if isinstance(element, list):
            result.extend(flatten_list(element))
        else:
            result.append(element)
    return result

flatten_list([[1, 2], [3, [4, 5]], 6])


[1, 2, 3, 4, 5, 6]

In [10]:
def get_nested_item(nested_list, index_list):
    """
    Retrieves an element from a nested list using a list of indices.

    Parameters:
    nested_list (list): The multi-level list.
    index_list (list): List of indices to navigate through the nested list.

    Returns:
    any: The target element.
    """
    for idx in index_list:
        nested_list = nested_list[idx]
    return nested_list

get_nested_item([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2])


6

In [11]:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The sum of all elements.
    """
    return sum(flatten(lst))

sum_nested([[1, 2], [3, [4, 5]], 6])

21

In [12]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to remove.

    Returns:
    list: The modified list.
    """
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

remove_element([[1, 2], [3, 2], [4, 5]],2)

[[1], [3], [4, 5]]

In [15]:
def get_max_value(nested_list):
    """
    Returns the highest number from a nested list.

    Parameters:
    nested_list (list): A list containing sublists.

    Returns:
    float: The highest number found.
    """
    return max(flatten_list(nested_list))

get_max_value([[1, 2], [3, [4, 5]], 6])


6

In [13]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to count.

    Returns:
    int: The number of occurrences.
    """
    return flatten(lst).count(elem)
count_occurrences([[1, 2], [2, 3], [2, 4]],2)

3

In [16]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list): The deeply nested list.

    Returns:
    list: A single flattened list.
    """
    return flatten(lst)

deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

[1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The average of all elements.
    """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)
average_nested([[1, 2], [3, 4], [5, 6]])

3.5

# Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [19]:
import numpy as np

# 1. Create an empty 2x2 array
empty_arr = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_arr)
print("---------------")

# 2. Create a 4x2 array filled with ones
ones_arr = np.ones((4, 2))
print("4x2 Array of Ones:\n", ones_arr)
print("---------------")

# 3. Create a 3x3 array filled with 5
filled_arr = np.full((3, 3), 5)
print("3x3 Array Filled with 5:\n", filled_arr)
print("---------------")

# 4. Create a zero array with the same shape as another array
sample_arr = np.array([[1, 2], [3, 4]])
zeros_arr = np.zeros_like(sample_arr)
print("Zero Array with Same Shape as Sample Array:\n", zeros_arr)
print("---------------")

# 5. Create an array of ones with the same shape as another array
ones_like_arr = np.ones_like(sample_arr)
print("Ones Array with Same Shape as Sample Array:\n", ones_like_arr)
print("---------------")

# 6. Convert a list to a NumPy array
num_list = [1, 2, 3, 4]
converted_arr = np.array(num_list)
print("NumPy Array from List:\n", converted_arr)


Empty 2x2 Array:
 [[2.71156043e-316 0.00000000e+000]
 [6.55002648e-310 5.33196831e-317]]
---------------
4x2 Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
3x3 Array Filled with 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
---------------
Zero Array with Same Shape as Sample Array:
 [[0 0]
 [0 0]]
---------------
Ones Array with Same Shape as Sample Array:
 [[1 1]
 [1 1]]
---------------
NumPy Array from List:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [21]:
import numpy as np

# 1. Create an array with values from 10 to 49
num_range = np.arange(10, 50)
print("Array from 10 to 49:\n", num_range)
print("---------------")

# 2. Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix (0 to 8):\n", matrix_3x3)
print("---------------")

# 3. Create a 3x3 identity matrix
identity_mat = np.eye(3)
print("3x3 Identity Matrix:\n", identity_mat)
print("---------------")

# 4. Create a random array of size 30 and find the mean
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()
print("Random Array (Size 30):\n", rand_arr)
print("Mean Value:", mean_val)
print("---------------")

# 5. Create a 10x10 array with random values and find the min and max
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("10x10 Random Array:\n", rand_10x10)
print("Min Value:", min_val)
print("Max Value:", max_val)
print("---------------")

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (index 4)
print("Zero Array (5th Element = 1):\n", zero_arr)
print("---------------")

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
rev_arr = arr[::-1]
print("Reversed Array:\n", rev_arr)
print("---------------")

# 8. Create a 2D array with 1 on the border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("2D Array (Border = 1, Inside = 0):\n", border_arr)
print("---------------")

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array (Size 30):
 [0.96587556 0.79823517 0.88028358 0.68793605 0.384036   0.8811841
 0.61035728 0.09428964 0.65966951 0.01714293 0.90576574 0.18677769
 0.37780689 0.9174688  0.57717545 0.34830872 0.76391862 0.7989148
 0.83238086 0.50408093 0.15514422 0.10319583 0.40407564 0.50708098
 0.991708   0.96470026 0.08325184 0.24238911 0.15820727 0.31617618]
Mean Value: 0.5372512553645984
---------------
10x10 Random Array:
 [[0.29602756 0.54743214 0.79683553 0.43936043 0.67962302 0.34224367
  0.98789104 0.81751703 0.7644241  0.61169405]
 [0.58327586 0.38884323 0.35511795 0.01940832 0.318648   0.80527756
  0.10584361 0.13818676 0.27099199 0.45907637]
 [0.45971407 0.39349633 0.50316085 0.6652

# Problem - 3: Array Operations:

In [22]:
import numpy as np

# Given arrays
a = np.array([[1, 2], [3, 5]])
b = np.array([[5, 6], [7, 8]])
vec1 = np.array([9, 10])
vec2 = np.array([11, 12])

# 1. Add the two arrays
sum_result = a + b
print("Sum of a and b:\n", sum_result)
print("---------------")

# 2. Subtract the two arrays
diff_result = a - b
print("Difference of a and b:\n", diff_result)
print("---------------")

# 3. Multiply the array by 2
mult_result = a * 2
print("a multiplied by 2:\n", mult_result)
print("---------------")

# 4. Square each element
squared_result = np.square(a)
print("Square of each element in a:\n", squared_result)
print("---------------")

# 5. Compute dot products
dot_vw = np.dot(vec1, vec2)
dot_av = np.dot(a, vec1)
dot_ab = np.dot(a, b)
print("Dot product of vec1 and vec2:", dot_vw)
print("Dot product of a and vec1:", dot_av)
print("Dot product of a and b:\n", dot_ab)
print("---------------")

# 6. Concatenate a and b along rows, vec1 and vec2 along columns
concat_rows = np.concatenate((a, b), axis=0)
concat_cols = np.vstack((vec1, vec2))
print("Concatenated a and b along rows:\n", concat_rows)
print("Concatenated vec1 and vec2 along columns:\n", concat_cols)
print("---------------")

# 7. Attempt to concatenate a and vec1 (expecting an error)
try:
    concat_av = np.concatenate((a, vec1))
except ValueError as e:
    print("Error:", e)
    print("Explanation: Shapes of a (2x2) and vec1 (2,) are not compatible for concatenation.")


Sum of a and b:
 [[ 6  8]
 [10 13]]
---------------
Difference of a and b:
 [[-4 -4]
 [-4 -3]]
---------------
a multiplied by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of each element in a:
 [[ 1  4]
 [ 9 25]]
---------------
Dot product of vec1 and vec2: 219
Dot product of a and vec1: [29 77]
Dot product of a and b:
 [[19 22]
 [50 58]]
---------------
Concatenated a and b along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated vec1 and vec2 along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Shapes of a (2x2) and vec1 (2,) are not compatible for concatenation.


# Problem - 4: Matrix Operations:

In [23]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Verify A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:\n", identity_matrix)
print("---------------")

# 2. Verify AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB ≠ BA?", not np.array_equal(AB, BA))
print("---------------")

# 3. Verify (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Is (AB)^T = B^T * A^T?", np.array_equal(AB_T, BT_AT))
print("---------------")

# Solve the system of linear equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

# Solve using inverse method
solution_inv = np.dot(np.linalg.inv(coeff_matrix), constants)
print("Solution using Inverse Method:", solution_inv)
print("---------------")

# Solve using np.linalg.solve
solution_direct = np.linalg.solve(coeff_matrix, constants)
print("Solution using np.linalg.solve:", solution_direct)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB ≠ BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T = B^T * A^T? True
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

In [27]:
import time
import numpy as np

# Function to measure execution time
def measure_time(func, *args):
    start = time.time()
    func(*args)
    end = time.time()
    return end - start

# 1. Element-wise Addition
def add_lists(lst1, lst2):
    return [a + b for a, b in zip(lst1, lst2)]

def add_arrays(arr1, arr2):
    return arr1 + arr2

# 2. Element-wise Multiplication
def multiply_lists(lst1, lst2):
    return [a * b for a, b in zip(lst1, lst2)]

def multiply_arrays(arr1, arr2):
    return arr1 * arr2

# 3. Dot Product
def dot_product_lists(lst1, lst2):
    return sum(a * b for a, b in zip(lst1, lst2))

def dot_product_arrays(arr1, arr2):
    return np.dot(arr1, arr2)

# 4. Matrix Multiplication
def multiply_matrices_lists(mat1, mat2):
    return [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]

def multiply_matrices_arrays(mat1, mat2):
    return np.dot(mat1, mat2)

# Initialize data
size = 1000000
lst1 = list(range(size))
lst2 = list(range(size, 2 * size))
arr1 = np.arange(size)
arr2 = np.arange(size, 2 * size)

matrix_size = 1000
mat1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]
npmat1 = np.array(mat1)
npmat2 = np.array(mat2)

# Measure execution times
print("1. Addition:")
print(f"Python Lists: {measure_time(add_lists, lst1, lst2):.6f} sec")
print(f"NumPy Arrays: {measure_time(add_arrays, arr1, arr2):.6f} sec")

print("\n2. Multiplication:")
print(f"Python Lists: {measure_time(multiply_lists, lst1, lst2):.6f} sec")
print(f"NumPy Arrays: {measure_time(multiply_arrays, arr1, arr2):.6f} sec")

print("\n3. Dot Product:")
print(f"Python Lists: {measure_time(dot_product_lists, lst1, lst2):.6f} sec")
print(f"NumPy Arrays: {measure_time(dot_product_arrays, arr1, arr2):.6f} sec")

print("\n4. Matrix Multiplication:")
print(f"Python Lists: {measure_time(multiply_matrices_lists, mat1, mat2):.6f} sec")
print(f"NumPy Arrays: {measure_time(multiply_matrices_arrays, npmat1, npmat2):.6f} sec")


1. Addition:
Python Lists: 0.073123 sec
NumPy Arrays: 0.002028 sec

2. Multiplication:
Python Lists: 0.072892 sec
NumPy Arrays: 0.002132 sec

3. Dot Product:
Python Lists: 0.082015 sec
NumPy Arrays: 0.001804 sec

4. Matrix Multiplication:
Python Lists: 146.293597 sec
NumPy Arrays: 1.257701 sec
